# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Hyde
tagline:          'A Jekyll theme'
description:      'Walk The Tech with <a href="https://in.linkedin.com/in/seemakadavan" target="_blank">@SeemaKadavan</a>'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://in.linkedin.com/in/seemakadavan

paginate:         5


github:
  repo:           https://github.com/poole/hyde
