# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Code Over Cappuccino
tagline:          'A Jekyll theme'
description:      'Walk The Tech with <a href="https://in.linkedin.com/in/seemakadavan" target="_blank">@SeemaKadavan</a>'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Seema Kadavan'
  url:            https://in.linkedin.com/in/seemakadavan

gems: [jekyll-paginate]
paginate:         5
paginate_path: "page:num"


github:
  repo:           https://github.com/poole/hyde
